# 🔢 50 Pandas + NumPy Integration Practice Questions

## 🔹 NP1–NP10: Array Conversions & Basic Integration

In [2]:
import numpy as np
import pandas as pd

### NP1. Create a NumPy array and convert it to a Pandas Series.
> 💡 **Hint:** `np.array([...])` creates the array. Pass it directly to `pd.Series(array, index=[...], name="...")`.

In [3]:
arr = np.array([1,2,3,4,5])

pd.Series(arr,name='array-series')

0    1
1    2
2    3
3    4
4    5
Name: array-series, dtype: int64

### NP2. Convert a 2D NumPy array to a Pandas DataFrame.
> 💡 **Hint:** `pd.DataFrame(np_2d_array, columns=[...])` — shape `(n, m)` gives `n` rows and `m` columns.

In [4]:
arr = np.arange(1,13).reshape(3,4)

pd.DataFrame(arr,columns=['c1','c2','c3','c4'])

   c1  c2  c3  c4
0   1   2   3   4
1   5   6   7   8
2   9  10  11  12

## NP3. Generate a random dataset using NumPy and store it in a DataFrame.
> 💡 **Hint:** Use `np.random.seed()` for reproducibility. Try `np.random.randn(n, m)` for normal distribution or `np.random.randint(lo, hi, n)` for integers.

In [5]:
arr = np.random.randint(1,50,10)

pd.DataFrame(arr,columns=['c1'])

   c1
0  23
1  33
2  45
3  43
4  30
5  25
6   6
7  16
8  46
9  37

## NP4. Perform element-wise operations using NumPy and Pandas.
> 💡 **Hint:** You can apply NumPy ufuncs directly on a Pandas Series: `np.sqrt(df["col"])`. The result is a Series.

In [6]:
arr = np.arange(45,55)
df = pd.DataFrame(arr,columns=['c1'])

np.sqrt(df['c1'])

0    6.708204
1    6.782330
2    6.855655
3    6.928203
4    7.000000
5    7.071068
6    7.141428
7    7.211103
8    7.280110
9    7.348469
Name: c1, dtype: float64

## NP5. Apply `np.mean` on DataFrame columns.
> 💡 **Hint:** `np.mean(df["col"])` works the same as `df["col"].mean()`. Apply to the `.values` array for pure NumPy speed: `np.mean(df["col"].values)`.

In [7]:
print(np.mean(df['c1'].values))

49.5

## NP6. Replace values using `np.where`.
> 💡 **Hint:** `np.where(condition, value_if_true, value_if_false)` — assign the result back to a column: `df["col"] = np.where(df["col"] > 50, "High", "Low")`.

In [8]:
np.where(df['c1'] % 2 == 0,1,0)

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1])

## NP7. Apply logarithmic transformation using `np.log`.
> 💡 **Hint:** `df["col_log"] = np.log(df["col"])`. Note: `np.log(0)` returns `-inf`. Use `np.log1p(x)` which computes `log(1 + x)` to safely handle zeros.

In [9]:
arr = np.arange(45,55)
df = pd.DataFrame(arr,columns=['c1'])

In [10]:
df['c1'] = np.log(df['c1'])
df

         c1
0  3.806662
1  3.828641
2  3.850148
3  3.871201
4  3.891820
5  3.912023
6  3.931826
7  3.951244
8  3.970292
9  3.988984

## NP8. Apply square root transformation using `np.sqrt`.
> 💡 **Hint:** `df["col_sqrt"] = np.sqrt(df["col"])`. Values must be non-negative; use `np.clip(df["col"], 0, None)` first if negatives are possible.

In [11]:
arr = np.arange(45,55)
df = pd.DataFrame(arr,columns=['c1'])

In [12]:
df['c1'] = np.sqrt(df['c1'])
df

         c1
0  6.708204
1  6.782330
2  6.855655
3  6.928203
4  7.000000
5  7.071068
6  7.141428
7  7.211103
8  7.280110
9  7.348469

## NP9. Use NumPy functions inside `apply()`.
> 💡 **Hint:** `df["col"].apply(lambda x: np.log(x))` — or pass the NumPy function directly: `df["col"].apply(np.log)`.

In [13]:
arr = np.arange(45,55)
df = pd.DataFrame(arr,columns=['c1'])

In [14]:
df['c1'].apply(lambda x : x ** 2)

0    2025
1    2116
2    2209
3    2304
4    2401
5    2500
6    2601
7    2704
8    2809
9    2916
Name: c1, dtype: int64

## NP10. Perform broadcasting in a DataFrame using NumPy.
> 💡 **Hint:** Extract `.values` (a 2D NumPy array) and multiply by a weights array: `df[cols].values @ weights_array`. The result can be assigned back as a new column.

In [15]:
arr = np.arange(1,13).reshape(3,4)

df = pd.DataFrame(arr,columns=['c1','c2','c3','c4'])

In [16]:
weight_array = np.arange(1,7).reshape(3,2)
df[['c1','c2']].values * weight_array

array([[ 1,  4],
       [15, 24],
       [45, 60]])

## 🔹 NP11–NP20: Data Filtering, Transformation & Statistics

## NP11. Filter DataFrame rows using a NumPy boolean mask.
> 💡 **Hint:** `mask = np.array(df["col"]) > threshold` creates a NumPy boolean array. Use `df[mask]` to filter

In [58]:
student = pd.DataFrame(
{

'name': ['aman', 'parv','naman',np.nan, 'mehek',np.nan, 'rishabh', np.nan, 'ashay',np.nan],
'college': ['bit', 'iit', 'vit', np.nan, np.nan, 'vlsi', 'ssit', np.nan, np.nan, 'git'],
'branch':['eee', 'it','cse',np.nan,'me','ce','civ','cse','bio',np.nan],
'cgpa' : [6.66,8.25,6.41,np.nan, 5.6,9.0,7.4,10,7.4,np.nan],
'package': [4,5,6,np.nan, 6,7,8,9,np.nan,np.nan]

} )

student

      name college branch   cgpa  package
0     aman     bit    eee   6.66      4.0
1     parv     iit     it   8.25      5.0
2    naman     vit    cse   6.41      6.0
3      NaN     NaN    NaN    NaN      NaN
4    mehek     NaN     me   5.60      6.0
5      NaN    vlsi     ce   9.00      7.0
6  rishabh    ssit    civ   7.40      8.0
7      NaN     NaN    cse  10.00      9.0
8    ashay     NaN    bio   7.40      NaN
9      NaN     git    NaN    NaN      NaN

In [21]:
mask = np.array(student["package"]) > 6
mask

array([False, False, False, False, False,  True,  True,  True, False,
       False])

## NP12. Count non-zero values in a column using NumPy.
> 💡 **Hint:** `np.count_nonzero(df["col"].values)` or `np.count_nonzero(df["col"].values != 0)`.

In [ ]:
np.count_nonzero(student['cgpa'].values) # it also count nan values as they are not zero

np.int64(10)

## NP13. Find unique values using `np.unique`.
> 💡 **Hint:** `np.unique(df["col"])` returns sorted unique values. Use `return_counts=True` to also get the frequency of each unique value.

In [27]:
np.unique(student['cgpa'])

array([ 5.6 ,  6.41,  6.66,  7.4 ,  8.25,  9.  , 10.  ,   nan])

## NP14. Flatten DataFrame values to a 1D NumPy array.
> 💡 **Hint:** `df[["col1","col2"]].values.flatten()` — the `.flatten()` method converts the 2D array to 1D row-by-row.

In [28]:
student[['name','college']].values.flatten()

array(['aman', 'bit', 'parv', 'iit', 'naman', 'vit', nan, nan, 'mehek',
       nan, nan, 'vlsi', 'rishabh', 'ssit', nan, nan, 'ashay', nan, nan,
       'git'], dtype=object)

## NP15. Reshape a NumPy array before creating a DataFrame.
> 💡 **Hint:** `np.arange(1, 25).reshape(6, 4)` creates a 6×4 array. Pass directly to `pd.DataFrame(arr, columns=[...])`.

In [31]:
arr = np.arange(1,25).reshape(6,4)

pd.DataFrame(arr,columns=['c1','c2','c3','c4'])

   c1  c2  c3  c4
0   1   2   3   4
1   5   6   7   8
2   9  10  11  12
3  13  14  15  16
4  17  18  19  20
5  21  22  23  24

## NP16. Perform matrix multiplication using `np.dot`.
> 💡 **Hint:** `np.dot(A, B)` or `A @ B`. Extract `.values` from DataFrames first, then wrap the result in a new `pd.DataFrame(result, columns=[...])`.

In [38]:
arr1 = np.arange(1,10).reshape(3,3)
arr2 = np.arange(11,20).reshape(3,3)

res = np.dot(arr1,arr2)

df = pd.DataFrame(res,columns=['c1','c2','c3'])
df

    c1   c2   c3
0   90   96  102
1  216  231  246
2  342  366  390

## NP17. Normalize data using NumPy (Min-Max scaling).
> 💡 **Hint:** `arr = df[cols].values` then `(arr - arr.min(axis=0)) / (arr.max(axis=0) - arr.min(axis=0))`. Use `axis=0` to operate column-wise.

In [40]:
arr = df['c1'].values

(arr - arr.min(axis=0)) / (arr.max(axis=0) - arr.min(axis=0))

array([0. , 0.5, 1. ])

## NP18. Standardize data using Z-score with NumPy.
> 💡 **Hint:** `z = (arr - arr.mean(axis=0)) / arr.std(axis=0)`. Wrap the result in a DataFrame using the original column names.

In [41]:
z = (arr - arr.mean(axis=0)) / arr.std(axis=0)
z

array([-1.22474487,  0.        ,  1.22474487])

## NP19. Clip values using `np.clip`.
> 💡 **Hint:** `np.clip(df["col"].values, a_min=lower_bound, a_max=upper_bound)` — values outside the range are replaced by the boundary values.

In [42]:
np.clip(student['cgpa'].values, a_min=0.0,a_max=10.0)

array([ 6.66,  8.25,  6.41,   nan,  5.6 ,  9.  ,  7.4 , 10.  ,  7.4 ,
         nan])

## NP20. Handle missing values using NumPy.
> 💡 **Hint:** Detect NaN with `np.isnan(arr)`. Fill using `np.nanmean(arr)` to compute the mean ignoring NaN, then replace: `arr[np.isnan(arr)] = np.nanmean(arr)`.

In [51]:
arr = np.array([ 6.66,  8.25,  6.41,  np.nan,  5.6 ,  9.  ,  7.4 , 10.  ,  7.4 ,np.nan])

arr[np.isnan(arr)] = np.nanmean(arr)
arr

array([ 6.66,  8.25,  6.41,  7.59,  5.6 ,  9.  ,  7.4 , 10.  ,  7.4 ,
        7.59])

## 🔹 NP21–NP30: Performance, Sorting & Statistical Analysis

### NP21. Compare NumPy vs Pandas performance on a large array.
> 💡 **Hint:** Use `time.time()` before and after each operation. Apply the same computation (`arr * 2 + 1`) to a raw NumPy array and a Pandas Series. NumPy is typically faster on pure numeric operations.

In [55]:
import time 

arr = np.arange(10000000)

start = time.time()
res = (arr * 2 + 1)
print(time.time() - start)

0.08613920211791992

In [56]:
s = pd.Series(arr)

start = time.time()
res = (s * 2 + 1)
print(time.time() - start)

0.1428380012512207

### NP22. Calculate cumulative sum using NumPy.
> 💡 **Hint:** `np.cumsum(df["col"].values)` — assign back: `df["cum_col"] = np.cumsum(df["col"])`.

In [61]:
student

      name college branch   cgpa  package  cum_col
0     aman     bit    eee   6.66      4.0      4.0
1     parv     iit     it   8.25      5.0      9.0
2    naman     vit    cse   6.41      6.0     15.0
3      NaN     NaN    NaN    NaN      NaN      NaN
4    mehek     NaN     me   5.60      6.0     21.0
5      NaN    vlsi     ce   9.00      7.0     28.0
6  rishabh    ssit    civ   7.40      8.0     36.0
7      NaN     NaN    cse  10.00      9.0     45.0
8    ashay     NaN    bio   7.40      NaN      NaN
9      NaN     git    NaN    NaN      NaN      NaN

In [60]:
student['cum_col'] = np.cumsum(student['package'])

## NP23. Use `np.argmax` and `np.argmin`.
> 💡 **Hint:** `np.argmax(df["col"].values)` returns the **integer position** of the maximum. Use `df.iloc[idx]` or `df.loc[idx]` to retrieve the full row.

In [84]:
indx = np.argmax(student['package'])

student.iloc[indx]

name        NaN
college     NaN
branch      cse
cgpa       10.0
package     9.0
cum_col    45.0
Name: 7, dtype: object

In [86]:
indx = np.argmin(student['package'])

student.iloc[indx]

name       aman
college     bit
branch      eee
cgpa       6.66
package     4.0
cum_col     4.0
Name: 0, dtype: object

In [87]:
indx = np.argmax(student['package'])

student.loc[indx]

name        NaN
college     NaN
branch      cse
cgpa       10.0
package     9.0
cum_col    45.0
Name: 7, dtype: object

## NP24. Sort values using NumPy `np.argsort`.
> 💡 **Hint:** `sorted_idx = np.argsort(df["col"].values)` gives indices that would sort the array. Use `df.iloc[sorted_idx]` to reorder the DataFrame.

In [88]:
sort = np.argsort(student['package'])

student.iloc[sort]

      name college branch   cgpa  package  cum_col
0     aman     bit    eee   6.66      4.0      4.0
1     parv     iit     it   8.25      5.0      9.0
2    naman     vit    cse   6.41      6.0     15.0
4    mehek     NaN     me   5.60      6.0     21.0
5      NaN    vlsi     ce   9.00      7.0     28.0
6  rishabh    ssit    civ   7.40      8.0     36.0
7      NaN     NaN    cse  10.00      9.0     45.0
3      NaN     NaN    NaN    NaN      NaN      NaN
8    ashay     NaN    bio   7.40      NaN      NaN
9      NaN     git    NaN    NaN      NaN      NaN

### NP25. Compute correlation using `np.corrcoef`.
> 💡 **Hint:** `np.corrcoef([df["col1"].values, df["col2"].values])` returns a 2×2 correlation matrix. Wrap in a DataFrame for readability. Compare with `df.corr()`.

In [91]:
mat = np.corrcoef([student['cgpa'], student['package']])
mat

array([[nan, nan],
       [nan, nan]])

In [97]:
student[['cgpa', 'package']].corr()

             cgpa   package
cgpa     1.000000  0.585583
package  0.585583  1.000000

Both codes calculate the Pearson correlation coefficient between cgpa and package and return a 2x2 correlation matrix. However, student.corr() is safer and better suited for DataFrames because it automatically handles missing data, whereas np.corrcoef() will fail or return NaN if your data contains missing values.

## NP26. Detect NaN values using NumPy.
> 💡 **Hint:** `np.isnan(arr)` returns a boolean array. Count NaN with `np.isnan(arr).sum()`. Compare with `pd.isnull(series)`.

In [106]:
arr = np.array([1,2,np.nan,4,np.nan,5,6,7,np.nan,np.nan,10])
# start = time.time()
np.isnan(arr).sum()
# print(time.time() - start) # numpy is faster

np.int64(4)

In [107]:
s = pd.Series(arr)
# start = time.time()

s.isnull().sum()
# print(time.time() - start)

np.int64(4)

## NP27. Create boolean masks using NumPy.
> 💡 **Hint:** `mask = (np.array(df["col1"]) > 80) & (np.array(df["col2"]) < 40)` — use `df[mask]` to filter.

In [111]:
mask = (np.array(student['cgpa']) > 8) & (np.array(student['package'] < 10))
student[mask]

   name college branch   cgpa  package  cum_col
1  parv     iit     it   8.25      5.0      9.0
5   NaN    vlsi     ce   9.00      7.0     28.0
7   NaN     NaN    cse  10.00      9.0     45.0

## NP28. Apply logical operations (`np.logical_and`, `np.logical_or`, `np.logical_not`).
> 💡 **Hint:** `np.logical_and(cond1, cond2)` is equivalent to `cond1 & cond2`. These functions work on NumPy arrays; convert Series with `.values` first.

In [124]:
log_and = np.logical_and((np.array(student['cgpa'].values) > 8),(np.array(student['package'].values) < 10))
student[log_and]

   name college branch   cgpa  package  cum_col
1  parv     iit     it   8.25      5.0      9.0
5   NaN    vlsi     ce   9.00      7.0     28.0
7   NaN     NaN    cse  10.00      9.0     45.0

In [123]:
log_or = np.logical_or((np.array(student['cgpa'].values) > 9),(np.array(student['package'].values) < 4))
student[log_or]

  name college branch  cgpa  package  cum_col
7  NaN     NaN    cse  10.0      9.0     45.0

In [125]:
log_not = np.logical_not((np.array(student['cgpa'].values) > 8),(np.array(student['package'].values) < 10))
student[log_not]

      name college branch  cgpa  package  cum_col
0     aman     bit    eee  6.66      4.0      4.0
2    naman     vit    cse  6.41      6.0     15.0
3      NaN     NaN    NaN   NaN      NaN      NaN
4    mehek     NaN     me  5.60      6.0     21.0
6  rishabh    ssit    civ  7.40      8.0     36.0
8    ashay     NaN    bio  7.40      NaN      NaN
9      NaN     git    NaN   NaN      NaN      NaN

## NP29. Apply `np.select` for multi-condition assignment.
> 💡 **Hint:** `df["Grade"] = np.select([df["Score"] >= 90, df["Score"] >= 75], ["A","B"], default="C")` — conditions are checked in order; the first match wins.

In [126]:
student["Grade"] = np.select([student["cgpa"] >= 9, student["cgpa"] >= 7], ["A","B"], default="C")

In [127]:
student

      name college branch   cgpa  package  cum_col Grade
0     aman     bit    eee   6.66      4.0      4.0     C
1     parv     iit     it   8.25      5.0      9.0     B
2    naman     vit    cse   6.41      6.0     15.0     C
3      NaN     NaN    NaN    NaN      NaN      NaN     C
4    mehek     NaN     me   5.60      6.0     21.0     C
5      NaN    vlsi     ce   9.00      7.0     28.0     A
6  rishabh    ssit    civ   7.40      8.0     36.0     B
7      NaN     NaN    cse  10.00      9.0     45.0     A
8    ashay     NaN    bio   7.40      NaN      NaN     B
9      NaN     git    NaN    NaN      NaN      NaN     C

## NP30. Multiply DataFrame columns element-wise using NumPy.
> 💡 **Hint:** `np.multiply(df["col1"].values, df["col2"].values)` is equivalent to `df["col1"] * df["col2"]` but uses NumPy internally.

In [128]:
res = np.multiply(student['package'].values,student['cum_col'].values)
res

array([ 16.,  45.,  90.,  nan, 126., 196., 288., 405.,  nan,  nan])

## 🔹 NP31–NP40: Data Wrangling & Conversion

### NP31. Shuffle dataset rows using NumPy.
> 💡 **Hint:** `shuffled_idx = np.random.permutation(df.index)` creates a random permutation of row indices. Use `df.loc[shuffled_idx].reset_index(drop=True)`.

In [130]:
shuffle = np.random.permutation(student.index)

student.loc[shuffle].reset_index()

   index     name college branch   cgpa  package  cum_col Grade
0      4    mehek     NaN     me   5.60      6.0     21.0     C
1      0     aman     bit    eee   6.66      4.0      4.0     C
2      7      NaN     NaN    cse  10.00      9.0     45.0     A
3      5      NaN    vlsi     ce   9.00      7.0     28.0     A
4      6  rishabh    ssit    civ   7.40      8.0     36.0     B
5      3      NaN     NaN    NaN    NaN      NaN      NaN     C
6      8    ashay     NaN    bio   7.40      NaN      NaN     B
7      2    naman     vit    cse   6.41      6.0     15.0     C
8      9      NaN     git    NaN    NaN      NaN      NaN     C
9      1     parv     iit     it   8.25      5.0      9.0     B

## NP32. Sample random rows using NumPy.
> 💡 **Hint:** `sample_idx = np.random.choice(df.index, size=N, replace=False)` — use `df.loc[sample_idx]`. Compare with `df.sample(N)`.

In [132]:
sample_ind = np.random.choice(student.index, size=2, replace=False)
student.loc[sample_ind]

  name college branch  cgpa  package  cum_col Grade
7  NaN     NaN    cse  10.0      9.0     45.0     A
5  NaN    vlsi     ce   9.0      7.0     28.0     A

In [133]:
student.sample(2)

   name college branch  cgpa  package  cum_col Grade
3   NaN     NaN    NaN   NaN      NaN      NaN     C
0  aman     bit    eee  6.66      4.0      4.0     C

## NP33. Calculate percentiles using NumPy.
> 💡 **Hint:** `np.percentile(df["col"].values, [25, 50, 75])` returns Q1, median, Q3. Use `np.percentile(arr, p)` for any percentile p in [0, 100].

In [136]:
np.percentile(student["cgpa"].values, [25, 50, 75])

array([nan, nan, nan])

## NP34. Calculate variance and standard deviation.
> 💡 **Hint:** `np.var(arr)` and `np.std(arr)` use `ddof=0` (population). Pandas `.var()` and `.std()` use `ddof=1` (sample). Be aware of this difference when comparing results.

In [143]:
arr = np.arange(10)
print(np.var(arr,ddof=0))
print(np.std(arr,ddof=0))

8.25
2.8722813232690143

In [144]:
s = pd.Series(arr)
print(s.var(ddof=1))
print(s.std(ddof=1))

9.166666666666666
3.0276503540974917

## NP35. Replace a DataFrame column with a NumPy array.
> 💡 **Hint:** `df["col"] = new_numpy_array` — the array length must match the number of rows. NumPy arrays are accepted directly.

In [146]:
new_arr = np.array([5,4,7,None,6,9,None,8,8,None])

student['package'] = new_arr

In [149]:
student

      name college branch   cgpa package  cum_col Grade
0     aman     bit    eee   6.66       5      4.0     C
1     parv     iit     it   8.25       4      9.0     B
2    naman     vit    cse   6.41       7     15.0     C
3      NaN     NaN    NaN    NaN    None      NaN     C
4    mehek     NaN     me   5.60       6     21.0     C
5      NaN    vlsi     ce   9.00       9     28.0     A
6  rishabh    ssit    civ   7.40    None     36.0     B
7      NaN     NaN    cse  10.00       8     45.0     A
8    ashay     NaN    bio   7.40       8      NaN     B
9      NaN     git    NaN    NaN    None      NaN     C

## NP36. Convert DataFrame to NumPy using `to_numpy()`.
> 💡 **Hint:** `df[["col1","col2"]].to_numpy()` returns a 2D NumPy array. This is the preferred method over `.values` as it accepts `dtype` and `na_value` parameters.

In [150]:
student[["name","package"]].to_numpy()

array([['aman', 5],
       ['parv', 4],
       ['naman', 7],
       [nan, None],
       ['mehek', 6],
       [nan, 9],
       ['rishabh', None],
       [nan, 8],
       ['ashay', 8],
       [nan, None]], dtype=object)

## NP37. Compare `.values` vs `.to_numpy()`.
> 💡 **Hint:** Both return a NumPy array. Key difference: `.to_numpy(dtype=np.float32)` accepts a `dtype` argument for explicit casting. Use `np.array_equal(a, b)` to confirm they produce the same result.

In [155]:
a = student["package"].to_numpy()
b = (np.array(student['package'].values))

np.array_equal(a,b)

True

## NP38. Slice a column using NumPy array indexing.
> 💡 **Hint:** Extract with `.values`, then apply NumPy slicing: `arr[::2]` (every other element), `arr[::-1]` (reversed), `arr[[0,3,5]]` (fancy indexing).

In [157]:
student['cgpa']

0     6.66
1     8.25
2     6.41
3      NaN
4     5.60
5     9.00
6     7.40
7    10.00
8     7.40
9      NaN
Name: cgpa, dtype: float64

In [159]:
print(student['cgpa'].values[::2])
print(student['cgpa'].values[::-1])
print(student['cgpa'].values[[0,3,5]])

[6.66 6.41 5.6  7.4  7.4 ]
[  nan  7.4  10.    7.4   9.    5.6    nan  6.41  8.25  6.66]
[6.66  nan 9.  ]

## NP39. Merge NumPy-generated data into a DataFrame.
> 💡 **Hint:** Create two DataFrames from NumPy arrays with a common key column (e.g., `ID`). Use `pd.merge(df1, df2, on="ID", how="outer")`.

In [ ]:
# 1. Generate data using NumPy
# Left dataset: IDs 1 to 4 and random scores
ids_1 = np.array([1, 2, 3, 4])
scores = np.random.randint(50, 100, size=4)

# Right dataset: IDs 3 to 6 and random ages (to show the 'outer' join effect)
ids_2 = np.array([3, 4, 5, 6])
ages = np.random.randint(18, 25, size=4)

# 2. Create DataFrames from the NumPy arrays
df1 = pd.DataFrame({
    'ID': ids_1,
    'Score': scores
})

df2 = pd.DataFrame({
    'ID': ids_2,
    'Age': ages
})

# 3. Merge the DataFrames using an outer join
merged_df = pd.merge(df1, df2, on='ID', how='outer')

print(merged_df)

   ID  Score   Age
0   1   73.0   NaN
1   2   56.0   NaN
2   3   72.0  21.0
3   4   62.0  19.0
4   5    NaN  20.0
5   6    NaN  24.0

## NP40. Apply rolling computation using NumPy.
> 💡 **Hint:** Use a list comprehension: `[np.mean(arr[max(0,i-w+1):i+1]) for i in range(len(arr))]` to manually compute a rolling mean with window `w`. Compare with `df["col"].rolling(w).mean()`.

In [176]:
arr = np.array([10,20,30,40,50])
w = 3

[np.mean(arr[max(0,i-w+1):i+1]) for i in range(len(arr))]

[np.float64(10.0),
 np.float64(15.0),
 np.float64(20.0),
 np.float64(30.0),
 np.float64(40.0)]

In [177]:
df = pd.DataFrame({'col': arr})
print(df["col"].rolling(w).mean())

0     NaN
1     NaN
2    20.0
3    30.0
4    40.0
Name: col, dtype: float64

## 🔹 NP41–NP50: ML-Ready Dataset Preparation

## NP41. Create a synthetic ML dataset using NumPy.
> 💡 **Hint:** Use `np.random.normal`, `np.random.randint`, `np.random.choice` to generate features. Use `np.where` or `np.select` to create a binary/multi-class label column.

In [184]:
# Set seed for reproducibility
np.random.seed(42)
n_samples = 1000

# 1. Generate Features using NumPy
# Continuous features (e.g., Age, Income)
age = np.random.randint(18, 70, size=n_samples)
income = np.random.normal(loc=50000, scale=15000, size=n_samples).round(2)

# Categorical feature (e.g., Education Level)
edu_levels = ["High School", "Bachelor", "Master", "PhD"]
education = np.random.choice(edu_levels, size=n_samples, p=[0.3, 0.4, 0.2, 0.1])

# 2. Define logic for the Target Label using np.select
# Let's create a multi-class label: Risk Category (Low, Medium, High)
# Based on conditions involving Age and Income
conditions = [
    (income > 65000) & (age > 30),  # High income, stable age -> Low Risk
    (income < 35000) | (age < 25),  # Low income or very young -> High Risk
]
choices = ["Low", "High"]

# np.select applies conditions; default value handles anything that doesn't match
risk_label = np.select(conditions, choices, default="Medium")

# 3. Combine into a structured Pandas DataFrame
dataset = pd.DataFrame(
    {
        "Age": age,
        "Income": income,
        "Education": education,
        "Risk_Rating": risk_label,
    }
)

# Preview the synthetic dataset
print(dataset.head())

   Age    Income Education Risk_Rating
0   56  25903.31       PhD        High
1   69  53051.95  Bachelor      Medium
2   46  38654.74  Bachelor      Medium
3   32  28666.19    Master        High
4   60  40301.41    Master      Medium

## NP42. Detect and replace outliers using NumPy.
> 💡 **Hint:** Compute Q1, Q3 with `np.percentile`. Define bounds as `Q1 - 1.5*IQR` and `Q3 + 1.5*IQR`. Use `np.clip(arr, lo, hi)` to replace outliers with boundary values.

In [179]:
arr = np.array([12, 15, 14, 1000, 19, 11, 16, -500, 14, 18, 15])

q1 = np.percentile(arr,25)
q3 = np.percentile(arr,75)

iqr = q3 - q1

lower_bo = q1 - 1.5 * iqr
upper_bo = q3 + 1.5 * iqr

clean_arr = np.clip(arr,lower_bo,upper_bo)

clean_arr

array([12., 15., 14., 23., 19., 11., 16.,  7., 14., 18., 15.])

### NP43. Scale dataset using NumPy functions.
> 💡 **Hint:** Apply Min-Max or Z-score scaling using NumPy on the `.values` array. Store results as new columns in the DataFrame.

In [185]:
# 1. Create a sample dataset
df = pd.DataFrame({"salary": [30000, 50000, 85000, 120000, 45000]})

# Extract the underlying NumPy array
X = df["salary"].values

# 2. Min-Max Scaling (Scales data between 0 and 1)
x_min = np.min(X)
x_max = np.max(X)
df["salary_minmax"] = (X - x_min) / (x_max - x_min)

# 3. Z-score Scaling (Scales data to mean = 0, standard deviation = 1)
x_mean = np.mean(X)
x_std = np.std(X)
df["salary_zscore"] = (X - x_mean) / x_std

# View the final DataFrame
print(df)

   salary  salary_minmax  salary_zscore
0   30000       0.000000      -1.108874
1   50000       0.222222      -0.492833
2   85000       0.611111       0.585239
3  120000       1.000000       1.663311
4   45000       0.166667      -0.646843

### NP44. Engineer new features using NumPy.
> 💡 **Hint:** Create polynomial features (`np.square`, `np.power`), log features (`np.log1p`), interaction features (column1 × column2), and binned features (`np.digitize`).

## NP45. Use exponential functions (`np.exp`).
> 💡 **Hint:** `np.exp(df["col"])` computes `e^x` for each element. This is the inverse of `np.log`. Useful for reverting log-transformed values.

## NP46. Compute differences using `np.diff`.
> 💡 **Hint:** `np.diff(df["col"].values)` returns an array of consecutive differences (length = n−1). Prepend `np.nan` and assign back: `df["col_diff"] = np.insert(np.diff(arr), 0, np.nan)`.

## NP47. Apply conditional encoding using NumPy.
> 💡 **Hint:** Use `np.select` with a list of conditions and corresponding integer codes to encode categorical columns numerically. For example: `DS → 0`, `ML → 1`, `AI → 2`.

### NP48. Build an ML-ready dataset (feature matrix X and label vector y).
> 💡 **Hint:** Select numeric feature columns → call `.to_numpy(dtype=np.float32)` → store as `X`. Create a binary label: `y = (df["col"] >= threshold).astype(int).to_numpy()`. Check shapes with `X.shape` and `y.shape`.

## NP49. Perform a mini data analysis project.
> 💡 **Hint:** Follow these steps: (1) Generate data with NumPy, (2) Store in DataFrame, (3) Clean with Pandas, (4) Engineer features with NumPy, (5) GroupBy analysis, (6) Detect outliers, (7) Export summary.

### NP50. Build an end-to-end pipeline using NumPy + Pandas.
> 💡 **Hint:** Chain all steps together:  
> 1. `np.random.seed(X)` → generate raw data  
> 2. `np.clip` → clean invalid values  
> 3. `np.log`, `np.square`, `np.where` → feature engineering  
> 4. `df.groupby().agg(...)` → statistical analysis  
> 5. IQR + `np.clip` → outlier removal  
> 6. `df[features].to_numpy(dtype=np.float32)` → ML feature matrix  
> 7. Export with `df.to_csv(...)`

## 🎯 Quick Hints Reference

| Task | NumPy Function | Pandas Equivalent |
|------|---------------|-------------------|
| Convert to array | `arr = df["col"].values` | `arr = df["col"].to_numpy()` |
| Conditional assign | `np.where(cond, a, b)` | `df.loc[cond, "col"] = val` |
| Multi-condition | `np.select([c1,c2],[v1,v2])` | `map()` / `pd.cut()` |
| Clip values | `np.clip(arr, lo, hi)` | `df["col"].clip(lo, hi)` |
| Count NaN | `np.isnan(arr).sum()` | `df.isnull().sum()` |
| Correlation | `np.corrcoef([a, b])` | `df.corr()` |
| Percentile | `np.percentile(arr, q)` | `df["col"].quantile(q/100)` |
| Cumulative sum | `np.cumsum(arr)` | `df["col"].cumsum()` |
| Sort indices | `np.argsort(arr)` | `df.sort_values(...).index` |
| Unique values | `np.unique(arr)` | `df["col"].unique()` |
| Reshape | `arr.reshape(r, c)` | — (use before DataFrame creation) |
| Min-Max scale | `(x - x.min()) / (x.max()-x.min())` | Manual or sklearn |
| Z-score | `(x - x.mean()) / x.std()` | Manual or sklearn |