# 🐼 100 Pandas Practical Questions
> **Instructions:** Try to solve each question on your own. Use the hints only if you are stuck.  
> Progress: Basic → Intermediate → Advanced  
> Recommended pace: 10–15 questions per day

---

In [1]:
import numpy as np
import pandas as pd

## 🔹 Section 1: Basics & Series (Q1–Q20)

### Q1. Create a Pandas Series from a list of integers.
> 💡 **Hint:** Use `pd.Series([...])`. The default index starts from 0.

In [2]:
pd.Series([1,2,3,4,5,])

0    1
1    2
2    3
3    4
4    5
dtype: int64

### Q2. Create a Series from a dictionary with custom index.
> 💡 **Hint:** Pass a `dict` to `pd.Series()`. Keys become the index labels automatically.

In [3]:
dict_pd = {
    'name': ['Aman','Kartik','Naman'],
    'marks':[89,90,67],
    'package':[6,10,3]
}

s = pd.Series(dict_pd)
print(s)

name       [Aman, Kartik, Naman]
marks               [89, 90, 67]
package               [6, 10, 3]
dtype: object

### Q3. Access elements using index labels.
> 💡 **Hint:** Use `s["label"]` for a single value, `s[["a","b"]]` for multiple, and `s["a":"c"]` for a range. Label slices are **inclusive** on both ends.

In [4]:
#single
print(s['name'])

#multiple
print(s[['name','marks']])

#range
print(s['name':'package'])

['Aman', 'Kartik', 'Naman']
name     [Aman, Kartik, Naman]
marks             [89, 90, 67]
dtype: object
name       [Aman, Kartik, Naman]
marks               [89, 90, 67]
package               [6, 10, 3]
dtype: object

### Q4. Perform arithmetic operations on a Series.
> 💡 **Hint:** Use `+`, `-`, `*`, `/`, `//`, `%`, `**` directly on the Series. Operations are **element-wise** and **index-aligned**.

In [5]:
marks = pd.Series([60,40,55,80])
grade_marks = pd.Series([1,2,3,4])

print(marks + grade_marks)
print(marks - grade_marks)
print(marks * grade_marks)
print(marks / grade_marks)
print(marks // grade_marks)
print(marks % grade_marks)
print(marks ** grade_marks)

0    61
1    42
2    58
3    84
dtype: int64
0    59
1    38
2    52
3    76
dtype: int64
0     60
1     80
2    165
3    320
dtype: int64
0    60.000000
1    20.000000
2    18.333333
3    20.000000
dtype: float64
0    60
1    20
2    18
3    20
dtype: int64
0    0
1    0
2    1
3    0
dtype: int64
0          60
1        1600
2      166375
3    40960000
dtype: int64

### Q5. Find mean, min, max of a Series.
> 💡 **Hint:** Use `.mean()`, `.min()`, `.max()`, `.sum()`, `.median()`, `.std()` directly on the Series.

In [6]:
s = pd.Series([34,55,63,12])

print(s.min())
print(s.max())
print(s.mean())
print(s.sum())
print(s.median())
print(s.std())

12
63
41.0
164
44.5
22.87647991569799

### Q6. Apply conditional filtering on a Series.
> 💡 **Hint:** Use a boolean mask: `s[s > 50]`. You can also chain conditions with `&` and `|`.

In [7]:
mask = s[s > 50]
print(mask)

1    55
2    63
dtype: int64

### Q7. Replace values in a Series.
> 💡 **Hint:** Use `.replace(old_val, new_val)` or pass a dictionary `{old: new}` to replace multiple values at once.

In [8]:
s

0    34
1    55
2    63
3    12
dtype: int64

In [9]:
s.replace(12,24)

0    34
1    55
2    63
3    24
dtype: int64

### Q8. Convert Series data type.
> 💡 **Hint:** Use `.astype(dtype)` — e.g., `.astype(int)`, `.astype(float)`, `.astype("category")`.

In [10]:
s.info()

<class 'pandas.Series'>
RangeIndex: 4 entries, 0 to 3
Series name: None
Non-Null Count  Dtype
--------------  -----
4 non-null      int64
dtypes: int64(1)
memory usage: 164.0 bytes

In [11]:
s.astype(int)

0    34
1    55
2    63
3    12
dtype: int64

In [12]:
s.astype(float)

0    34.0
1    55.0
2    63.0
3    12.0
dtype: float64

In [13]:
s.astype('category')

0    34
1    55
2    63
3    12
dtype: category
Categories (4, int64): [12, 34, 55, 63]

### Q9. Check for null values in Series.
> 💡 **Hint:** Use `.isnull()` (returns boolean Series) or `.isnull().sum()` for a count.

In [14]:
null = pd.Series([1,2,3,4,None,6])

null.isnull().sum()

np.int64(1)

### Q10. Fill missing values in Series.
> 💡 **Hint:** Use `.fillna(value)` for constant, `.fillna(s.mean())` for mean, `.ffill()` for forward fill, `.bfill()` for backward fill.

In [15]:
null.fillna(5)

0    1.0
1    2.0
2    3.0
3    4.0
4    5.0
5    6.0
dtype: float64

In [16]:
null.fillna(null.mean())

0    1.0
1    2.0
2    3.0
3    4.0
4    3.2
5    6.0
dtype: float64

In [17]:
null.ffill()

0    1.0
1    2.0
2    3.0
3    4.0
4    4.0
5    6.0
dtype: float64

In [18]:
null.bfill()

0    1.0
1    2.0
2    3.0
3    4.0
4    6.0
5    6.0
dtype: float64

### Q11. Create DataFrame from a list.
> 💡 **Hint:** Use `pd.DataFrame(list_of_lists, columns=[...])`. Each inner list becomes one row.

In [19]:
student_data = [
    [100,120,80],
    [90,100,76],
    [10,14,5]
]

student = pd.DataFrame(student_data,columns=['iq','marks','package'])
print(student)

    iq  marks  package
0  100    120       80
1   90    100       76
2   10     14        5

### Q12. Create DataFrame from a dictionary.
> 💡 **Hint:** Use `pd.DataFrame({col: values})`. Keys become column names; values must have equal length.

In [20]:
student_dict = {
    'iq': [100,120,80],
    'marks': [90,100,76],
    'package':[10,14,5]
}

student = pd.DataFrame(student_dict)
student

    iq  marks  package
0  100     90       10
1  120    100       14
2   80     76        5

### Q13. Create DataFrame from list of dictionaries.
> 💡 **Hint:** Use `pd.DataFrame([{...}, {...}])`. Each dict is a row; missing keys become `NaN`.

In [21]:
pd.DataFrame([{'name': 'Aman','marks':78},{'name':'Parv','marks':58},{}])

   name  marks
0  Aman   78.0
1  Parv   58.0
2   NaN    NaN

### Q14. Display DataFrame structure (shape, columns, dtypes).
> 💡 **Hint:** Use `df.shape`, `df.columns`, `df.dtypes`, `df.info()`, and `df.describe()`.

In [22]:
print(student.shape)
print(student.columns)
print(student.dtypes)
print(student.info())

(3, 3)
Index(['iq', 'marks', 'package'], dtype='str')
iq         int64
marks      int64
package    int64
dtype: object
<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   iq       3 non-null      int64
 1   marks    3 non-null      int64
 2   package  3 non-null      int64
dtypes: int64(3)
memory usage: 204.0 bytes
None

### Q15. Select single column from DataFrame.
> 💡 **Hint:** Use `df["col_name"]` — this returns a **Series**. You can also use `df.col_name` (dot notation).

In [23]:
student['package']

0    10
1    14
2     5
Name: package, dtype: int64

In [24]:
student.marks

0     90
1    100
2     76
Name: marks, dtype: int64

### Q16. Select multiple columns.
> 💡 **Hint:** Use `df[["col1", "col2"]]` with a list inside the brackets — this returns a **DataFrame**.

In [25]:
student[['iq','package']]

    iq  package
0  100       10
1  120       14
2   80        5

### Q17. Add new column with scalar value.
> 💡 **Hint:** `df["new_col"] = 10` — the scalar is **broadcast** to all rows automatically.

In [26]:
student['country'] = 'India'
student

    iq  marks  package country
0  100     90       10   India
1  120    100       14   India
2   80     76        5   India

### Q18. Add column using Series.
> 💡 **Hint:** `df["new_col"] = pd.Series([...])`. The Series index must align with the DataFrame index.

In [27]:
student['name'] = pd.Series(['Aman','Parv','Naman'])
student

    iq  marks  package country   name
0  100     90       10   India   Aman
1  120    100       14   India   Parv
2   80     76        5   India  Naman

### Q19. Rename columns using `rename()`.
> 💡 **Hint:** Use `df.rename(columns={"old": "new"})`. Add `inplace=True` to modify in-place.

In [28]:
student.rename(columns={'package':'LPA'},inplace=True)
student

    iq  marks  LPA country   name
0  100     90   10   India   Aman
1  120    100   14   India   Parv
2   80     76    5   India  Naman

### Q20. Rename multiple columns.
> 💡 **Hint:** Pass a dictionary with multiple key-value pairs to `rename(columns={...})`.

In [29]:
student.rename(columns={'marks':'percent','LPA':'package'})
# student

    iq  percent  package country   name
0  100       90       10   India   Aman
1  120      100       14   India   Parv
2   80       76        5   India  Naman

## 🔹 Section 2: Indexing, Selection & Slicing (Q21–Q40)

### Q21. Select rows using `loc`.
> 💡 **Hint:** `df.loc[label]` for a single row, `df.loc[label1:label2]` for a range. **Inclusive on both ends.**

In [30]:
student.loc[1]
student.loc[0:2]

    iq  marks  LPA country   name
0  100     90   10   India   Aman
1  120    100   14   India   Parv
2   80     76    5   India  Naman

### Q22. Select rows using `iloc`.
> 💡 **Hint:** `df.iloc[0]` for first row, `df.iloc[1:4]` for rows 1–3. **Exclusive on the end** (Python-style).

In [31]:
student.iloc[0]
student.iloc[1:3]

    iq  marks  LPA country   name
1  120    100   14   India   Parv
2   80     76    5   India  Naman

### Q23. Access specific row and column.
> 💡 **Hint:** `df.loc[row_label, "col_name"]` or `df.iloc[row_pos, col_pos]` for a single cell.

In [32]:
student.loc[0,'LPA']
student.iloc[1,2]

np.int64(14)

### Q24. Select subset using multiple rows & columns.
> 💡 **Hint:** `df.loc[[r1,r2], ["col1","col2"]]` or `df.iloc[[0,1], [0,2]]`.

In [33]:
student.loc[[0,1],['name','LPA']]
student.iloc[[0,1], [0,2]]

    iq  LPA
0  100   10
1  120   14

### Q25. Apply conditional filtering using `loc`.
> 💡 **Hint:** `df.loc[df["col"] > value, ["col1","col2"]]` — pass a boolean Series as the row selector.

In [34]:
student.loc[student['LPA'] > 10, ['name','iq']]

   name   iq
1  Parv  120

### Q26. Slice rows using index range.
> 💡 **Hint:** Use `df.iloc[start:end]` for position-based slicing or `df.loc[label1:label2]` for label-based slicing.

In [35]:
student.iloc[0:3]
student.loc['iq':'LPA']

Empty DataFrame
Columns: [iq, marks, LPA, country, name]
Index: []

### Q27. Slice columns using labels.
> 💡 **Hint:** `df.loc[:, "col1":"col3"]` — selects all rows, columns from col1 to col3 (label-inclusive).

In [36]:
student.loc[:,'iq':'LPA']

    iq  marks  LPA
0  100     90   10
1  120    100   14
2   80     76    5

### Q28. Slice columns using position.
> 💡 **Hint:** `df.iloc[:, 1:4]` — selects all rows, columns at positions 1, 2, 3.

In [37]:
student.iloc[:, 1:4]

   marks  LPA country
0     90   10   India
1    100   14   India
2     76    5   India

### Q29. Perform combined row & column slicing.
> 💡 **Hint:** `df.loc[row_condition, ["col1","col2"]]` or `df.iloc[0:5, [0, 2, 4]]`.

In [38]:
student.loc[0:2,['iq','LPA']]

    iq  LPA
0  100   10
1  120   14
2   80    5

In [39]:
student.iloc[0:5, [0, 2, 4]]

    iq  LPA   name
0  100   10   Aman
1  120   14   Parv
2   80    5  Naman

### Q30. Set a column as index.
> 💡 **Hint:** Use `df.set_index("col_name")`. Add `inplace=True` to modify without reassigning.

In [40]:
student.set_index('name',inplace=True)

In [41]:
student

        iq  marks  LPA country
name
Aman   100     90   10   India
Parv   120    100   14   India
Naman   80     76    5   India

### Q31. Create hierarchical index (MultiIndex).
> 💡 **Hint:** `df.set_index(["col1","col2"])` — pass a **list** of column names to create a MultiIndex.

In [42]:
student.set_index(['iq','marks'])

           LPA country
iq  marks
100 90      10   India
120 100     14   India
80  76       5   India

### Q32. Reset index.
> 💡 **Hint:** `df.reset_index()` — moves the current index back to a column. Use `inplace=True` to modify in-place.

In [43]:
student.reset_index()

    name   iq  marks  LPA country
0   Aman  100     90   10   India
1   Parv  120    100   14   India
2  Naman   80     76    5   India

In [44]:
student

        iq  marks  LPA country
name
Aman   100     90   10   India
Parv   120    100   14   India
Naman   80     76    5   India

### Q33. Reset multi-index.
> 💡 **Hint:** `df.reset_index()` on a MultiIndex DataFrame flattens both index levels back to columns.

In [45]:
student.reset_index()

    name   iq  marks  LPA country
0   Aman  100     90   10   India
1   Parv  120    100   14   India
2  Naman   80     76    5   India

### Q34. Convert index to column.
> 💡 **Hint:** `df.reset_index()` by default moves the index to a column. Use `drop=False` (default) to keep it.

In [46]:
student.reset_index(drop=False)

    name   iq  marks  LPA country
0   Aman  100     90   10   India
1   Parv  120    100   14   India
2  Naman   80     76    5   India

### Q35. Use drop option in `reset_index`.
> 💡 **Hint:** `df.reset_index(drop=True)` discards the old index completely instead of converting it to a column.

In [47]:
student.reset_index(drop=True)

    iq  marks  LPA country
0  100     90   10   India
1  120    100   14   India
2   80     76    5   India

### Q36. Perform label-based indexing.
> 💡 **Hint:** Use `df.loc[label]` — works with any index type (string, integer, datetime labels).

In [48]:
student.loc['Aman']

iq           100
marks         90
LPA           10
country    India
Name: Aman, dtype: object

### Q37. Perform position-based indexing.
> 💡 **Hint:** Use `df.iloc[0]` — always integer-based, regardless of the index type.

In [49]:
student.iloc[0]

iq           100
marks         90
LPA           10
country    India
Name: Aman, dtype: object

### Q38. Access first N rows.
> 💡 **Hint:** `df.head(N)` — default N is 5.

In [50]:
student.head()

        iq  marks  LPA country
name
Aman   100     90   10   India
Parv   120    100   14   India
Naman   80     76    5   India

### Q39. Access last N rows.
> 💡 **Hint:** `df.tail(N)` — default N is 5.

In [51]:
student.tail()

        iq  marks  LPA country
name
Aman   100     90   10   India
Parv   120    100   14   India
Naman   80     76    5   India

### Q40. Extract random sample from DataFrame.
> 💡 **Hint:** `df.sample(n=5)` for random rows, `df.sample(frac=0.2)` for 20% of rows. Set `random_state` for reproducibility.

In [52]:
student.sample(frac=0.2)
student.sample(2,random_state=1)

        iq  marks  LPA country
name
Aman   100     90   10   India
Naman   80     76    5   India

## 🔹 Section 3: Data Cleaning (Q41–Q60)

In [53]:
ipl = pd.read_csv('Datasets\ipl-matches.csv')

<>:1: SyntaxWarning: "\i" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\i"? A raw string is also an option.
<>:1: SyntaxWarning: "\i" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\i"? A raw string is also an option.
C:\Users\himan\AppData\Local\Temp\ipykernel_3396\2941609372.py:1: SyntaxWarning: "\i" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\i"? A raw string is also an option.
  ipl = pd.read_csv('Datasets\ipl-matches.csv')

In [54]:
movies = pd.read_csv('Datasets\movies.csv')

<>:1: SyntaxWarning: "\m" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\m"? A raw string is also an option.
<>:1: SyntaxWarning: "\m" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\m"? A raw string is also an option.
C:\Users\himan\AppData\Local\Temp\ipykernel_3396\3377783915.py:1: SyntaxWarning: "\m" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\m"? A raw string is also an option.
  movies = pd.read_csv('Datasets\movies.csv')

### Q41. Detect missing values using `isnull()`.
> 💡 **Hint:** `df.isnull()` returns a boolean DataFrame. Use `.isnull().sum()` for column-wise counts or `.isnull().any()` to check if any exist.

In [55]:
movies.isnull().sum().any()

np.True_

## Q42. Drop missing values using `dropna()`.
> 💡 **Hint:** `df.dropna()` drops any row with a NaN. Use `axis=1` for columns, `subset=["col"]` for specific columns, and `thresh=N` to keep rows with at least N non-null values.

In [56]:
ipl.head(1)

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
0,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,N,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon

In [57]:
ipl.dropna(subset=['SuperOver'])

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
0,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,N,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon
1,1312199,Ahmedabad,2022-05-27,2022,Qualifier 2,Royal Challengers Bangalore,Rajasthan Royals,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,field,N,Rajasthan Royals,Wickets,7.0,NaN,JC Buttler,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",CB Gaffaney,Nitin Menon
2,1312198,Kolkata,2022-05-25,2022,Eliminator,Royal Challengers Bangalore,Lucknow Super Giants,"Eden Gardens, Kolkata",Lucknow Super Giants,field,N,Royal Challengers Bangalore,Runs,14.0,NaN,RM Patidar,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['Q de Kock', 'KL Rahul', 'M Vohra', 'DJ Hooda...",J Madanagopal,MA Gough
3,1312197,Kolkata,2022-05-24,2022,Qualifier 1,Rajasthan Royals,Gujarat Titans,"Eden Gardens, Kolkata",Gujarat Titans,field,N,Gujarat Titans,Wickets,7.0,NaN,DA Miller,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",BNJ Oxenford,VK Sharma
4,1304116,Mumbai,2022-05-22,2022,70,Sunrisers Hyderabad,Punjab Kings,"Wankhede Stadium, Mumbai",Sunrisers Hyderabad,bat,N,Punjab Kings,Wickets,5.0,NaN,Harpreet Brar,"['PK Garg', 'Abhishek Sharma', 'RA Tripathi', ...","['JM Bairstow', 'S Dhawan', 'M Shahrukh Khan',...",AK Chaudhary,NA Patwardhan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
945,335986,Kolkata,2008-04-20,2007/08,4,Kolkata Knight Riders,Deccan Chargers,Eden Gardens,Deccan Chargers,bat,N,Kolkata Knight Riders,Wickets,5.0,NaN,DJ Hussey,"['WP Saha', 'BB McCullum', 'RT Ponting', 'SC G...","['AC Gilchrist', 'Y Venugopal Rao', 'VVS Laxma...",BF Bowden,K Hariharan
946,335985,Mumbai,2008-04-20,2007/08,5,Mumbai Indians,Royal Challengers Bangalore,Wankhede Stadium,Mumbai Indians,bat,N,Royal Challengers Bangalore,Wickets,5.0,NaN,MV Boucher,"['L Ronchi', 'ST Jayasuriya', 'DJ Thornely', '...","['S Chanderpaul', 'R Dravid', 'LRPL Taylor', '...",SJ Davis,DJ Harper
947,335984,Delhi,2008-04-19,2007/08,3,Delhi Daredevils,Rajasthan Royals,Feroz Shah Kotla,Rajasthan Royals,bat,N,Delhi Daredevils,Wickets,9.0,NaN,MF Maharoof,"['G Gambhir', 'V Sehwag', 'S Dhawan', 'MK Tiwa...","['T Kohli', 'YK Pathan', 'SR Watson', 'M Kaif'...",Aleem Dar,GA Pratapkumar
948,335983,Chandigarh,2008-04-19,2007/08,2,Kings XI Punjab,Chennai Super Kings,"Punjab Cricket Association Stadium, Mohali",Chennai Super Kings,bat,N,Chennai Super Kings,Runs,33.0,NaN,MEK Hussey,"['K Goel', 'JR Hopes', 'KC Sangakkara', 'Yuvra...","['PA Patel', 'ML Hayden', 'MEK Hussey', 'MS Dh...",MR Benson,SL Shastri
949,335982,Bangalore,2008-04-18,2007/08,1,Royal Challengers Bangalore,Kolkata Knight Riders,M Chinnaswamy Stadium,Royal Challengers Bangalore,field,N,Kolkata Knight Riders,Runs,140.0,NaN,BB McCullum,"['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...","['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...",Asad Rauf,RE Koertzen

### Q43. Fill missing values with a constant.
> 💡 **Hint:** `df.fillna(0)` or `df["col"].fillna("Unknown")`. You can also pass a dict to fill different columns with different values.

In [58]:
ipl.fillna(0)
ipl['City'].fillna("Unknown")

0       Ahmedabad
1       Ahmedabad
2         Kolkata
3         Kolkata
4          Mumbai
          ...
945       Kolkata
946        Mumbai
947         Delhi
948    Chandigarh
949     Bangalore
Name: City, Length: 950, dtype: str

### Q44. Fill missing values using mean/median.
> 💡 **Hint:** `df["col"].fillna(df["col"].mean())` or `df["col"].fillna(df["col"].median())`.

In [59]:
vk = pd.read_csv('Datasets\kohli_ipl.csv')

<>:1: SyntaxWarning: "\k" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\k"? A raw string is also an option.
<>:1: SyntaxWarning: "\k" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\k"? A raw string is also an option.
C:\Users\himan\AppData\Local\Temp\ipykernel_3396\1242372793.py:1: SyntaxWarning: "\k" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\k"? A raw string is also an option.
  vk = pd.read_csv('Datasets\kohli_ipl.csv')

In [60]:
vk.head(1)

   match_no  runs
0         1     1

In [61]:
vk["runs"].fillna(vk["runs"].mean())

0       1
1      23
2      13
3      12
4       1
       ..
210     0
211    20
212    73
213    25
214     7
Name: runs, Length: 215, dtype: int64

In [62]:
vk["runs"].fillna(vk["runs"].median())

0       1
1      23
2      13
3      12
4       1
       ..
210     0
211    20
212    73
213    25
214     7
Name: runs, Length: 215, dtype: int64

## Q45. Use forward fill and backward fill.
> 💡 **Hint:** `df.ffill()` propagates the last valid value forward. `df.bfill()` fills using the next valid value.

In [63]:
vk.ffill()

     match_no  runs
0           1     1
1           2    23
2           3    13
3           4    12
4           5     1
..        ...   ...
210       211     0
211       212    20
212       213    73
213       214    25
214       215     7

[215 rows x 2 columns]

In [64]:
vk.bfill()

     match_no  runs
0           1     1
1           2    23
2           3    13
3           4    12
4           5     1
..        ...   ...
210       211     0
211       212    20
212       213    73
213       214    25
214       215     7

[215 rows x 2 columns]

## Q46. Convert data type using `astype()`.
> 💡 **Hint:** `df["col"].astype(int)` or `df["col"].astype("category")`. Use `errors="coerce"` inside `pd.to_numeric()` to handle invalid values.

In [65]:
ipl.info()

<class 'pandas.DataFrame'>
RangeIndex: 950 entries, 0 to 949
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ID               950 non-null    int64
 1   City             899 non-null    str
 2   Date             950 non-null    str
 3   Season           950 non-null    str
 4   MatchNumber      950 non-null    str
 5   Team1            950 non-null    str
 6   Team2            950 non-null    str
 7   Venue            950 non-null    str
 8   TossWinner       950 non-null    str
 9   TossDecision     950 non-null    str
 10  SuperOver        946 non-null    str
 11  WinningTeam      946 non-null    str
 12  WonBy            950 non-null    str
 13  Margin           932 non-null    float64
 14  method           19 non-null     str
 15  Player_of_Match  946 non-null    str
 16  Team1Players     950 non-null    str
 17  Team2Players     950 non-null    str
 18  Umpire1          950 non-null    str
 19  Umpire2          950 non-null    str
dtypes: float64(1), int64(1), str(18)
memory usage: 148.6 KB

In [66]:
ipl['ID'].astype('int32')

0      1312200
1      1312199
2      1312198
3      1312197
4      1304116
        ...
945     335986
946     335985
947     335984
948     335983
949     335982
Name: ID, Length: 950, dtype: int32

In [67]:
ipl["Season"].astype("category")

0         2022
1         2022
2         2022
3         2022
4         2022
        ...
945    2007/08
946    2007/08
947    2007/08
948    2007/08
949    2007/08
Name: Season, Length: 950, dtype: category
Categories (15, str): ['2007/08', '2009', '2009/10', '2011', ..., '2019', '2020/21', '2021', '2022']

In [68]:
ipl['SuperOver'] = pd.to_numeric(ipl['SuperOver'],errors='coerce')
ipl.head()

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
0,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,NaN,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon
1,1312199,Ahmedabad,2022-05-27,2022,Qualifier 2,Royal Challengers Bangalore,Rajasthan Royals,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,field,NaN,Rajasthan Royals,Wickets,7.0,NaN,JC Buttler,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",CB Gaffaney,Nitin Menon
2,1312198,Kolkata,2022-05-25,2022,Eliminator,Royal Challengers Bangalore,Lucknow Super Giants,"Eden Gardens, Kolkata",Lucknow Super Giants,field,NaN,Royal Challengers Bangalore,Runs,14.0,NaN,RM Patidar,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['Q de Kock', 'KL Rahul', 'M Vohra', 'DJ Hooda...",J Madanagopal,MA Gough
3,1312197,Kolkata,2022-05-24,2022,Qualifier 1,Rajasthan Royals,Gujarat Titans,"Eden Gardens, Kolkata",Gujarat Titans,field,NaN,Gujarat Titans,Wickets,7.0,NaN,DA Miller,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",BNJ Oxenford,VK Sharma
4,1304116,Mumbai,2022-05-22,2022,70,Sunrisers Hyderabad,Punjab Kings,"Wankhede Stadium, Mumbai",Sunrisers Hyderabad,bat,NaN,Punjab Kings,Wickets,5.0,NaN,Harpreet Brar,"['PK Garg', 'Abhishek Sharma', 'RA Tripathi', ...","['JM Bairstow', 'S Dhawan', 'M Shahrukh Khan',...",AK Chaudhary,NA Patwardhan

# Q47. Clean string column using `.str.lower()`.
> 💡 **Hint:** Access the `.str` accessor first: `df["col"].str.lower()`. Similarly `.str.upper()`, `.str.title()`.

In [69]:
movies.head(1)

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
0,Uri: The Surgical Strike,tt8291224,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Uri:_The_Surgica...,Uri: The Surgical Strike,Uri: The Surgical Strike,0,2019,138,Action|Drama|War,8.4,35112,Divided over five chapters the film chronicle...,Indian army special forces execute a covert op...,NaN,Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...,4 wins,11 January 2019 (USA)

In [70]:
movies['wiki_link'].str.lower()

0       https://en.wikipedia.org/wiki/uri:_the_surgica...
1             https://en.wikipedia.org/wiki/battalion_609
2       https://en.wikipedia.org/wiki/the_accidental_p...
3           https://en.wikipedia.org/wiki/why_cheat_india
4           https://en.wikipedia.org/wiki/evening_shadows
                              ...
1624    https://en.wikipedia.org/wiki/tera_mera_saath_...
1625    https://en.wikipedia.org/wiki/yeh_zindagi_ka_s...
1626        https://en.wikipedia.org/wiki/sabse_bada_sukh
1627                  https://en.wikipedia.org/wiki/daaka
1628               https://en.wikipedia.org/wiki/humsafar
Name: wiki_link, Length: 1629, dtype: str

In [71]:
movies['summary'].str.upper()

0       INDIAN ARMY SPECIAL FORCES EXECUTE A COVERT OP...
1       THE STORY OF BATTALION 609 REVOLVES AROUND A C...
2       EXPLORES MANMOHAN SINGH'S TENURE AS THE PRIME ...
3       THE MOVIE FOCUSES ON EXISTING MALPRACTICES IN ...
4       UNDER THE 'EVENING SHADOWS'  TRUTH OFTEN PLAYS...
                              ...
1624    A MAN IS TORN BETWEEN HIS HANDICAPPED BROTHER ...
1625    A SINGER FINDS OUT SHE WAS ADOPTED WHEN THE ED...
1626    VILLAGE BORN LALLOO RE-LOCATES TO BOMBAY  AND ...
1627    SHINDA TRIES ROBBING A BANK SO HE CAN BE WEALT...
1628    ASHAR AND KHIRAD ARE FORCED TO GET MARRIED DUE...
Name: summary, Length: 1629, dtype: str

In [72]:
movies['title_y'].str.title()

0            Uri: The Surgical Strike
1                       Battalion 609
2       The Accidental Prime Minister
3                     Why Cheat India
4                     Evening Shadows
                    ...
1624            Tera Mera Saath Rahen
1625             Yeh Zindagi Ka Safar
1626                  Sabse Bada Sukh
1627                            Daaka
1628                         Humsafar
Name: title_y, Length: 1629, dtype: str

## Q48. Trim whitespace in strings.
> 💡 **Hint:** `df["col"].str.strip()` removes leading and trailing spaces. Use `.str.lstrip()` / `.str.rstrip()` for one side.

In [73]:
movies['title_y'].str.strip()

0            Uri: The Surgical Strike
1                       Battalion 609
2       The Accidental Prime Minister
3                     Why Cheat India
4                     Evening Shadows
                    ...
1624            Tera Mera Saath Rahen
1625             Yeh Zindagi Ka Safar
1626                  Sabse Bada Sukh
1627                            Daaka
1628                         Humsafar
Name: title_y, Length: 1629, dtype: str

In [74]:
movies['title_y'].str.lstrip()

0            Uri: The Surgical Strike
1                       Battalion 609
2       The Accidental Prime Minister
3                     Why Cheat India
4                     Evening Shadows
                    ...
1624            Tera Mera Saath Rahen
1625             Yeh Zindagi Ka Safar
1626                  Sabse Bada Sukh
1627                            Daaka
1628                         Humsafar
Name: title_y, Length: 1629, dtype: str

In [75]:
movies['title_y'].str.rstrip()

0            Uri: The Surgical Strike
1                       Battalion 609
2       The Accidental Prime Minister
3                     Why Cheat India
4                     Evening Shadows
                    ...
1624            Tera Mera Saath Rahen
1625             Yeh Zindagi Ka Safar
1626                  Sabse Bada Sukh
1627                            Daaka
1628                         Humsafar
Name: title_y, Length: 1629, dtype: str

### Q49. Replace substring in column.
> 💡 **Hint:** `df["col"].str.replace("old", "new")`. Add `regex=True` for pattern-based replacement.

In [76]:
ipl.head(1)

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
0,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,NaN,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon

In [77]:
ipl['MatchNumber'].str.replace('Final','Finals')

0           Finals
1      Qualifier 2
2       Eliminator
3      Qualifier 1
4               70
          ...
945              4
946              5
947              3
948              2
949              1
Name: MatchNumber, Length: 950, dtype: str

## Q50. Extract part of string using `.str`.
> 💡 **Hint:** `df["col"].str[:3]` for first 3 chars. Use `.str.split("@").str[1]` to extract after a delimiter.

In [78]:
movies['wiki_link'].str[0:4]

0       http
1       http
2       http
3       http
4       http
        ...
1624    http
1625    http
1626    http
1627    http
1628    http
Name: wiki_link, Length: 1629, dtype: str

In [79]:
movies['wiki_link'].str.split("w").str[1]

0       ikipedia.org/
1       ikipedia.org/
2       ikipedia.org/
3       ikipedia.org/
4       ikipedia.org/
            ...
1624    ikipedia.org/
1625    ikipedia.org/
1626    ikipedia.org/
1627    ikipedia.org/
1628    ikipedia.org/
Name: wiki_link, Length: 1629, dtype: object

### Q51. Detect duplicate rows.
> 💡 **Hint:** `df.duplicated()` returns a boolean Series. Use `df[df.duplicated()]` to see the actual duplicate rows.

In [80]:
movies[movies.duplicated()]

Empty DataFrame
Columns: [title_x, imdb_id, poster_path, wiki_link, title_y, original_title, is_adult, year_of_release, runtime, genres, imdb_rating, imdb_votes, story, summary, tagline, actors, wins_nominations, release_date]
Index: []

### Q52. Remove duplicates using `drop_duplicates()`.
> 💡 **Hint:** `df.drop_duplicates()` keeps the first occurrence by default. Use `subset=["col"]` to check specific columns, and `keep="last"` or `keep=False`.

In [81]:
vk.drop_duplicates()

     match_no  runs
0           1     1
1           2    23
2           3    13
3           4    12
4           5     1
..        ...   ...
210       211     0
211       212    20
212       213    73
213       214    25
214       215     7

[215 rows x 2 columns]

In [82]:
vk.drop_duplicates(subset=['runs'],keep=False)

     match_no  runs
36         37    37
40         41    71
62         63    45
64         65    36
73         74    65
80         81    93
81         82    99
85         86    49
109       110    82
111       112    44
116       117    79
118       119    80
121       122    52
122       123   108
125       126   109
127       128   113
132       133    28
133       134    64
136       137    55
144       145    92
147       148    68
156       157    46
159       160    84
172       173    29
177       178    90
197       198    53

### Q53. Rename row labels.
> 💡 **Hint:** `df.rename(index={old_label: new_label})`.

In [83]:
student.rename(index={'name':'country'})
student

        iq  marks  LPA country
name
Aman   100     90   10   India
Parv   120    100   14   India
Naman   80     76    5   India


### Q54. Handle inconsistent data.
> 💡 **Hint:** Use `.str.strip().str.lower()` to normalize strings. Use `.replace({...})` to map inconsistent values to a standard form.

## Q55. Replace values in DataFrame.
> 💡 **Hint:** `df.replace("old", "new")` works DataFrame-wide. Pass a dict `{old: new}` or nested dict `{"col": {old: new}}` for column-specific replacement.

In [84]:
student.replace(100,99)

        iq  marks  LPA country
name
Aman    99     90   10   India
Parv   120     99   14   India
Naman   80     76    5   India

### Q56. Detect outliers in a column.
> 💡 **Hint:** Use the **IQR method**: compute Q1, Q3, IQR = Q3–Q1. Outliers are values below `Q1 - 1.5*IQR` or above `Q3 + 1.5*IQR`. Alternatively use Z-score: `|z| > 3`.

In [85]:
# 1. Calculate Q1 (25th percentile) and Q3 (75th percentile)
Q1 = student['marks'].quantile(0.25)
Q3 = student['marks'].quantile(0.75)

# 2. Calculate the Interquartile Range (IQR)
IQR = Q3 - Q1

# 3. Define the upper and lower bounds
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

# 4. Filter the DataFrame to find the outliers
outliers = student[(student['marks'] < lower_bound) | (student['marks'] > upper_bound)]
print(outliers)

Empty DataFrame
Columns: [iq, marks, LPA, country]
Index: []

### Q57. Handle outliers using clipping.
> 💡 **Hint:** `df["col"].clip(lower=lo, upper=hi)` replaces values outside the bounds with the boundary values.

In [86]:
vk["runs"].clip(lower=0, upper=100)

0       1
1      23
2      13
3      12
4       1
       ..
210     0
211    20
212    73
213    25
214     7
Name: runs, Length: 215, dtype: int64

## Q58. Standardize column names.
> 💡 **Hint:** `df.columns = df.columns.str.strip().str.lower().str.replace(" ", "_")` — clean all column names in one line.

In [87]:
movies.head(1)

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
0,Uri: The Surgical Strike,tt8291224,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Uri:_The_Surgica...,Uri: The Surgical Strike,Uri: The Surgical Strike,0,2019,138,Action|Drama|War,8.4,35112,Divided over five chapters the film chronicle...,Indian army special forces execute a covert op...,NaN,Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...,4 wins,11 January 2019 (USA)

In [88]:
movies.title_y = movies.title_y.str.strip().str.lower().str.replace(" ", "_")
movies.head(1)

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
0,Uri: The Surgical Strike,tt8291224,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Uri:_The_Surgica...,uri:_the_surgical_strike,Uri: The Surgical Strike,0,2019,138,Action|Drama|War,8.4,35112,Divided over five chapters the film chronicle...,Indian army special forces execute a covert op...,NaN,Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...,4 wins,11 January 2019 (USA)

### Q59. Handle mixed data types in a column.
> 💡 **Hint:** Use `pd.to_numeric(df["col"], errors="coerce")` to convert to numbers, turning invalid strings into `NaN`.

In [89]:
pd.to_numeric(ipl["SuperOver"], errors="coerce")

0     NaN
1     NaN
2     NaN
3     NaN
4     NaN
       ..
945   NaN
946   NaN
947   NaN
948   NaN
949   NaN
Name: SuperOver, Length: 950, dtype: float64

### Q60. Remove special characters from text data.
> 💡 **Hint:** `df["col"].str.replace(r"[^a-zA-Z0-9 ]", "", regex=True)` — use regex to keep only alphanumeric characters.

In [90]:
movies["poster_path"].str.replace(r"[^a-zA-Z0-9 ]", "", regex=True)

0       httpsuploadwikimediaorgwikipediaenthumb33bURIN...
1                                                     NaN
2       httpsuploadwikimediaorgwikipediaenthumbaa1TheA...
3       httpsuploadwikimediaorgwikipediaenthumbaa2WhyC...
4                                                     NaN
                              ...
1624    httpsuploadwikimediaorgwikipediaen22bTeraMeraS...
1625    httpsuploadwikimediaorgwikipediaenthumb221YehZ...
1626                                                  NaN
1627    httpsuploadwikimediaorgwikipediaenthumb445Daak...
1628    httpsuploadwikimediaorgwikipediaenthumb441Flag...
Name: poster_path, Length: 1629, dtype: str

## 🔹 Section 4: Data Manipulation (Q61–Q80)

### Q61. Filter rows using AND condition.
> 💡 **Hint:** `df[(df["col1"] > val) & (df["col2"] == "x")]` — wrap each condition in parentheses and use `&`.

In [91]:
ipl.head(1)

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
0,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,NaN,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon

In [92]:
ipl[(ipl['MatchNumber'] == 'Final') & (ipl['WinningTeam'] == 'Gujarat Titans')]

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
0,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,NaN,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon

### Q62. Filter rows using OR condition.
> 💡 **Hint:** `df[(df["col1"] > val) | (df["col2"] == "x")]` — use `|` between conditions.

In [93]:
ipl[(ipl['Season'] == '2022') | (ipl['City'] == 'Ahmedabad')]

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
0,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,NaN,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon
1,1312199,Ahmedabad,2022-05-27,2022,Qualifier 2,Royal Challengers Bangalore,Rajasthan Royals,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,field,NaN,Rajasthan Royals,Wickets,7.0,NaN,JC Buttler,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",CB Gaffaney,Nitin Menon
2,1312198,Kolkata,2022-05-25,2022,Eliminator,Royal Challengers Bangalore,Lucknow Super Giants,"Eden Gardens, Kolkata",Lucknow Super Giants,field,NaN,Royal Challengers Bangalore,Runs,14.0,NaN,RM Patidar,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['Q de Kock', 'KL Rahul', 'M Vohra', 'DJ Hooda...",J Madanagopal,MA Gough
3,1312197,Kolkata,2022-05-24,2022,Qualifier 1,Rajasthan Royals,Gujarat Titans,"Eden Gardens, Kolkata",Gujarat Titans,field,NaN,Gujarat Titans,Wickets,7.0,NaN,DA Miller,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",BNJ Oxenford,VK Sharma
4,1304116,Mumbai,2022-05-22,2022,70,Sunrisers Hyderabad,Punjab Kings,"Wankhede Stadium, Mumbai",Sunrisers Hyderabad,bat,NaN,Punjab Kings,Wickets,5.0,NaN,Harpreet Brar,"['PK Garg', 'Abhishek Sharma', 'RA Tripathi', ...","['JM Bairstow', 'S Dhawan', 'M Shahrukh Khan',...",AK Chaudhary,NA Patwardhan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
527,733979,Ahmedabad,2014-05-05,2014,25,Rajasthan Royals,Kolkata Knight Riders,"Sardar Patel Stadium, Motera",Kolkata Knight Riders,field,NaN,Rajasthan Royals,Runs,10.0,NaN,PV Tambe,"['AM Rahane', 'KK Nair', 'SV Samson', 'SR Wats...","['RV Uthappa', 'G Gambhir', 'AD Russell', 'MK ...",NJ Llong,CK Nandan
811,419129,Ahmedabad,2010-03-28,2009/10,24,Rajasthan Royals,Chennai Super Kings,"Sardar Patel Stadium, Motera",Rajasthan Royals,bat,NaN,Rajasthan Royals,Runs,17.0,NaN,NV Ojha,"['MJ Lumb', 'NV Ojha', 'FY Fazal', 'YK Pathan'...","['M Vijay', 'ML Hayden', 'SK Raina', 'MS Dhoni...",SS Hazare,SJA Taufel
813,419126,Ahmedabad,2010-03-26,2009/10,22,Rajasthan Royals,Deccan Chargers,"Sardar Patel Stadium, Motera",Deccan Chargers,bat,NaN,Rajasthan Royals,Wickets,8.0,NaN,YK Pathan,"['MJ Lumb', 'NV Ojha', 'YK Pathan', 'FY Fazal'...","['AC Gilchrist', 'VVS Laxman', 'HH Gibbs', 'A ...",HDPK Dharmasena,SJA Taufel
822,419118,Ahmedabad,2010-03-20,2009/10,13,Rajasthan Royals,Kolkata Knight Riders,"Sardar Patel Stadium, Motera",Rajasthan Royals,bat,NaN,Rajasthan Royals,Runs,34.0,NaN,AA Jhunjhunwala,"['MJ Lumb', 'NV Ojha', 'FY Fazal', 'AA Jhunjhu...","['MK Tiwary', 'BJ Hodge', 'CA Pujara', 'SC Gan...",RE Koertzen,RB Tiffin
829,419111,Ahmedabad,2010-03-15,2009/10,6,Rajasthan Royals,Delhi Daredevils,"Sardar Patel Stadium, Motera",Delhi Daredevils,field,NaN,Delhi Daredevils,Wickets,6.0,NaN,V Sehwag,"['SA Asnodkar', 'GC Smith', 'NV Ojha', 'YK Pat...","['G Gambhir', 'V Sehwag', 'TM Dilshan', 'AB de...",BG Jerling,RE Koertzen

### Q63. Filter rows using NOT condition.
> 💡 **Hint:** `df[~(df["col"] == "val")]` — use `~` to negate a boolean condition.

In [94]:
ipl[~(ipl['TossWinner'] == 'Sunrisers Hyderabad')]

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
0,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,NaN,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon
1,1312199,Ahmedabad,2022-05-27,2022,Qualifier 2,Royal Challengers Bangalore,Rajasthan Royals,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,field,NaN,Rajasthan Royals,Wickets,7.0,NaN,JC Buttler,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",CB Gaffaney,Nitin Menon
2,1312198,Kolkata,2022-05-25,2022,Eliminator,Royal Challengers Bangalore,Lucknow Super Giants,"Eden Gardens, Kolkata",Lucknow Super Giants,field,NaN,Royal Challengers Bangalore,Runs,14.0,NaN,RM Patidar,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['Q de Kock', 'KL Rahul', 'M Vohra', 'DJ Hooda...",J Madanagopal,MA Gough
3,1312197,Kolkata,2022-05-24,2022,Qualifier 1,Rajasthan Royals,Gujarat Titans,"Eden Gardens, Kolkata",Gujarat Titans,field,NaN,Gujarat Titans,Wickets,7.0,NaN,DA Miller,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",BNJ Oxenford,VK Sharma
5,1304115,Mumbai,2022-05-21,2022,69,Delhi Capitals,Mumbai Indians,"Wankhede Stadium, Mumbai",Mumbai Indians,field,NaN,Mumbai Indians,Wickets,5.0,NaN,JJ Bumrah,"['PP Shaw', 'DA Warner', 'MR Marsh', 'RR Pant'...","['Ishan Kishan', 'RG Sharma', 'D Brevis', 'Til...",Nitin Menon,Tapan Sharma
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
945,335986,Kolkata,2008-04-20,2007/08,4,Kolkata Knight Riders,Deccan Chargers,Eden Gardens,Deccan Chargers,bat,NaN,Kolkata Knight Riders,Wickets,5.0,NaN,DJ Hussey,"['WP Saha', 'BB McCullum', 'RT Ponting', 'SC G...","['AC Gilchrist', 'Y Venugopal Rao', 'VVS Laxma...",BF Bowden,K Hariharan
946,335985,Mumbai,2008-04-20,2007/08,5,Mumbai Indians,Royal Challengers Bangalore,Wankhede Stadium,Mumbai Indians,bat,NaN,Royal Challengers Bangalore,Wickets,5.0,NaN,MV Boucher,"['L Ronchi', 'ST Jayasuriya', 'DJ Thornely', '...","['S Chanderpaul', 'R Dravid', 'LRPL Taylor', '...",SJ Davis,DJ Harper
947,335984,Delhi,2008-04-19,2007/08,3,Delhi Daredevils,Rajasthan Royals,Feroz Shah Kotla,Rajasthan Royals,bat,NaN,Delhi Daredevils,Wickets,9.0,NaN,MF Maharoof,"['G Gambhir', 'V Sehwag', 'S Dhawan', 'MK Tiwa...","['T Kohli', 'YK Pathan', 'SR Watson', 'M Kaif'...",Aleem Dar,GA Pratapkumar
948,335983,Chandigarh,2008-04-19,2007/08,2,Kings XI Punjab,Chennai Super Kings,"Punjab Cricket Association Stadium, Mohali",Chennai Super Kings,bat,NaN,Chennai Super Kings,Runs,33.0,NaN,MEK Hussey,"['K Goel', 'JR Hopes', 'KC Sangakkara', 'Yuvra...","['PA Patel', 'ML Hayden', 'MEK Hussey', 'MS Dh...",MR Benson,SL Shastri
949,335982,Bangalore,2008-04-18,2007/08,1,Royal Challengers Bangalore,Kolkata Knight Riders,M Chinnaswamy Stadium,Royal Challengers Bangalore,field,NaN,Kolkata Knight Riders,Runs,140.0,NaN,BB McCullum,"['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...","['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...",Asad Rauf,RE Koertzen

## Q64. Sort DataFrame by column values.
> 💡 **Hint:** `df.sort_values("col")`. Use `ascending=False` for descending, `by=["col1","col2"]` for multi-column sort.

In [95]:
vk.sort_values('runs',ascending=False)
vk.sort_values(by=['match_no','runs'],ascending=False)

     match_no  runs
214       215     7
213       214    25
212       213    73
211       212    20
210       211     0
..        ...   ...
4           5     1
3           4    12
2           3    13
1           2    23
0           1     1

[215 rows x 2 columns]

### Q65. Sort DataFrame by index.
> 💡 **Hint:** `df.sort_index()`. Use `axis=1` to sort columns alphabetically.

In [96]:
vk.sort_index(axis=1)

     match_no  runs
0           1     1
1           2    23
2           3    13
3           4    12
4           5     1
..        ...   ...
210       211     0
211       212    20
212       213    73
213       214    25
214       215     7

[215 rows x 2 columns]

## Q66. Add calculated column.
> 💡 **Hint:** `df["new"] = df["col1"] * df["col2"]` or use `.assign(new=lambda x: ...)` for chainable operations.

In [97]:
student['iq + marks'] = student['iq'] + student['marks']
student

        iq  marks  LPA country  iq + marks
name
Aman   100     90   10   India         190
Parv   120    100   14   India         220
Naman   80     76    5   India         156

### Q67. Remove column using `drop()`.
> 💡 **Hint:** `df.drop(columns=["col1","col2"])`. Always use the `columns=` parameter to be explicit.

In [98]:
student.drop(columns=['iq + marks'])

        iq  marks  LPA country
name
Aman   100     90   10   India
Parv   120    100   14   India
Naman   80     76    5   India

### Q68. Remove rows using `drop()`.
> 💡 **Hint:** `df.drop(index=[0, 3])` removes rows with those index labels.

In [99]:
vk.drop(index=[0,2])

     match_no  runs
1           2    23
3           4    12
4           5     1
5           6     9
6           7    34
..        ...   ...
210       211     0
211       212    20
212       213    73
213       214    25
214       215     7

[213 rows x 2 columns]

### Q69. Use `map()` on a column.
> 💡 **Hint:** `df["col"].map({"a": 1, "b": 2})` substitutes values using a dict. Pass a function for element-wise transformation.

In [100]:
vk["runs"].map({"a": 1, "b": 2})

0     NaN
1     NaN
2     NaN
3     NaN
4     NaN
       ..
210   NaN
211   NaN
212   NaN
213   NaN
214   NaN
Name: runs, Length: 215, dtype: float64

## Q70. Apply function using `apply()`.
> 💡 **Hint:** `df["col"].apply(func)` for a Series. `df.apply(func, axis=0)` column-wise, `df.apply(func, axis=1)` row-wise.

In [106]:
vk[vk['runs'].apply(lambda x : x % 2 == 0)]

     match_no  runs
3           4    12
6           7    34
7           8     0
10         11    10
11         12    38
..        ...   ...
206       207     0
208       209    58
209       210    30
210       211     0
211       212    20

[109 rows x 2 columns]

### Q71. Apply element-wise using `applymap()` / `map()`.
> 💡 **Hint:** In older pandas use `df.applymap(func)`. In pandas ≥ 2.1 use `df.map(func)` for element-wise operations on the entire DataFrame.

In [108]:
vk.map(lambda x : x ** 2)

     match_no  runs
0           1     1
1           4   529
2           9   169
3          16   144
4          25     1
..        ...   ...
210     44521     0
211     44944   400
212     45369  5329
213     45796   625
214     46225    49

[215 rows x 2 columns]

### Q72. Chain multiple operations.
> 💡 **Hint:** Use method chaining with `(df.copy().loc[...].sort_values(...)[cols].assign(...).reset_index(drop=True))` — wrap in parentheses for multi-line readability.

In [123]:
res = (vk.copy().sort_values(by='runs').assign(runs=lambda x : x['runs'] ** 2).reset_index(drop=True))
print(res)

     match_no   runs
0           8      0
1          87      0
2          93      0
3          91      0
4         206      0
..        ...    ...
210       164  10000
211       120  10000
212       123  11664
213       126  11881
214       128  12769

[215 rows x 2 columns]

### Q73. Normalize numeric columns (Min-Max).
> 💡 **Hint:** `(df["col"] - df["col"].min()) / (df["col"].max() - df["col"].min())` — result is in range [0, 1].

In [124]:
(vk['runs'] - vk['runs'].min()) / (vk['runs'].max()) - (vk['runs'].min())

0      0.008850
1      0.203540
2      0.115044
3      0.106195
4      0.008850
         ...
210    0.000000
211    0.176991
212    0.646018
213    0.221239
214    0.061947
Name: runs, Length: 215, dtype: float64

## Q74. Scale numerical data (Z-score standardization).
> 💡 **Hint:** `(df["col"] - df["col"].mean()) / df["col"].std()` — result has mean=0 and std=1.

In [125]:
(vk['runs'] - vk['runs'].mean()) / (vk['runs'].std())

0     -1.138240
1     -0.299500
2     -0.680745
3     -0.718870
4     -1.138240
         ...
210   -1.176365
211   -0.413873
212    1.606729
213   -0.223250
214   -0.909493
Name: runs, Length: 215, dtype: float64

## Q75. Rank values in a column.
> 💡 **Hint:** `df["col"].rank()` — use `ascending=False` for descending rank, `method="dense"` to avoid gaps.

In [128]:
movies['title_y'].rank(ascending=False)

0         96.0
1       1451.0
2        173.0
3         48.0
4       1160.0
         ...
1624     184.0
1625      21.0
1626     344.0
1627    1300.0
1628     979.0
Name: title_y, Length: 1629, dtype: float64

## Q76. Create bins using `cut()`.
> 💡 **Hint:** `pd.cut(df["col"], bins=4)` for equal-width bins or `pd.cut(df["col"], bins=[0,25,50,75,100], labels=["Low","Mid","High","Top"])` for custom intervals.

In [132]:
pd.cut(ipl["Margin"], bins=4)

0       (0.855, 37.25]
1       (0.855, 37.25]
2       (0.855, 37.25]
3       (0.855, 37.25]
4       (0.855, 37.25]
            ...
945     (0.855, 37.25]
946     (0.855, 37.25]
947     (0.855, 37.25]
948     (0.855, 37.25]
949    (109.75, 146.0]
Name: Margin, Length: 950, dtype: category
Categories (4, interval[float64, right]): [(0.855, 37.25] < (37.25, 73.5] < (73.5, 109.75] < (109.75, 146.0]]


### Q77. Create bins using `qcut()`.
> 💡 **Hint:** `pd.qcut(df["col"], q=4)` for **equal-frequency** (quantile-based) bins. Use `labels=["Q1","Q2","Q3","Q4"]` for named bins.

### Q78. Count unique values.
> 💡 **Hint:** `df["col"].nunique()` for the count, `df["col"].value_counts()` for frequency per unique value.

In [134]:
vk['runs'].nunique() # 78
vk['runs'].value_counts()

runs
0     9
1     8
12    8
9     7
35    6
     ..
46    1
84    1
29    1
90    1
53    1
Name: count, Length: 78, dtype: int64

## Q79. Replace multiple values at once.
> 💡 **Hint:** `df.replace({"col": {"old1": "new1", "old2": "new2"}})` or use a list: `df.replace(["old1","old2"], "new")`.

In [136]:
student.replace({'LPA':{10:12,14:20,5:7}})

        iq  marks  LPA country  iq + marks
name
Aman   100     90   12   India         190
Parv   120    100   20   India         220
Naman   80     76    7   India         156

## Q80. Create flag column based on condition.
> 💡 **Hint:** `df["flag"] = (df["col"] > threshold).astype(int)` — converts True/False to 1/0. Or use `np.where(condition, 1, 0)`.

## 🔹 Section 5: Iteration, GroupBy & Pivot (Q81–Q100)

## Q81. Iterate over rows using `iterrows()`.
> 💡 **Hint:** `for idx, row in df.iterrows():` — `idx` is the index label, `row` is a Series with column values.

In [139]:
for idx,row in student.iterrows():
    print(idx,row)
    print()

Aman iq              100
marks            90
LPA              10
country       India
iq + marks      190
Name: Aman, dtype: object

Parv iq              120
marks           100
LPA              14
country       India
iq + marks      220
Name: Parv, dtype: object

Naman iq               80
marks            76
LPA               5
country       India
iq + marks      156
Name: Naman, dtype: object

## Q82. Iterate using `itertuples()`.
> 💡 **Hint:** `for row in df.itertuples():` — `row.col_name` accesses values. **Faster** than `iterrows()` due to named tuples.

In [140]:
for row in student.itertuples():
    print(row)
    print()

Pandas(Index='Aman', iq=100, marks=90, LPA=10, country='India', _5=190)

Pandas(Index='Parv', iq=120, marks=100, LPA=14, country='India', _5=220)

Pandas(Index='Naman', iq=80, marks=76, LPA=5, country='India', _5=156)

## Q83. Iterate over columns.
> 💡 **Hint:** `for col in df.columns:` then access `df[col]`. Or use `df.items()` which yields `(col_name, Series)` pairs.

In [148]:
for col in student.items():
    print(col)
    print()

('iq', name
Aman     100
Parv     120
Naman     80
Name: iq, dtype: int64)

('marks', name
Aman      90
Parv     100
Naman     76
Name: marks, dtype: int64)

('LPA', name
Aman     10
Parv     14
Naman     5
Name: LPA, dtype: int64)

('country', name
Aman     India
Parv     India
Naman    India
Name: country, dtype: str)

('iq + marks', name
Aman     190
Parv     220
Naman    156
Name: iq + marks, dtype: int64)

## Q84. Avoid iteration using vectorization.
> 💡 **Hint:** Replace `for` loops with direct column operations: `df["new"] = df["a"] * 2 + 1` instead of a loop over rows.

In [149]:
# student['new package'] = student['LPA'] + 5

        iq  marks  LPA country  iq + marks
name
Aman   100     90   10   India         190
Parv   120    100   14   India         220
Naman   80     76    5   India         156

## Q85. Group data using `groupby()`.
> 💡 **Hint:** `df.groupby("col")["value_col"].mean()` — specify the grouping key and the aggregation in one line.

In [150]:
student.groupby('LPA')['marks'].mean()

LPA
5      76.0
10     90.0
14    100.0
Name: marks, dtype: float64

### Q86. Calculate sum per group.
> 💡 **Hint:** `df.groupby("col")["value"].sum()` — replace `sum` with any aggregation function.

In [151]:
student.groupby('LPA')['marks'].sum()

LPA
5      76
10     90
14    100
Name: marks, dtype: int64

### Q87. Calculate multiple aggregations.
> 💡 **Hint:** `df.groupby("col").agg({"col1": "mean", "col2": "sum"})` or `df.groupby("col").agg(name=("col","func"))` for named aggregation.

In [152]:
student.groupby('LPA').agg({'marks':'sum','iq':'mean'})

     marks     iq
LPA
5       76   80.0
10      90  100.0
14     100  120.0

## Q88. Group by multiple columns.
> 💡 **Hint:** `df.groupby(["col1","col2"])["value"].mean()` — pass a list of column names.

In [153]:
student.groupby(['iq','marks'])['LPA'].mean()

iq   marks
80   76        5.0
100  90       10.0
120  100      14.0
Name: LPA, dtype: float64

### Q89. Filter grouped data.
> 💡 **Hint:** `df.groupby("col").filter(lambda g: g["value"].mean() > threshold)` — keeps entire groups satisfying the condition.

In [155]:
student.groupby('marks').filter(lambda x : x['marks'] > 90)

       iq  marks  LPA country  iq + marks
name
Parv  120    100   14   India         220

## Q90. Transform grouped data using `transform()`.
> 💡 **Hint:** `df.groupby("col")["value"].transform("mean")` — returns a Series **same size as the original DataFrame** filled with group statistics.

In [156]:
student.groupby('marks')['LPA'].transform('mean')

name
Aman     10.0
Parv     14.0
Naman     5.0
Name: LPA, dtype: float64

## Q91. Apply custom function in groupby.
> 💡 **Hint:** `df.groupby("col")["value"].agg(lambda s: s.max() - s.min())` — pass any function that takes a Series and returns a scalar.

In [162]:
student.groupby('LPA')['marks'].agg(lambda x : x.max() - x.mean())

LPA
5     0.0
10    0.0
14    0.0
Name: marks, dtype: float64

### Q92. Create basic pivot table.
> 💡 **Hint:** `pd.pivot_table(df, values="val", index="row_col", columns="col_col", aggfunc="mean")`.

In [169]:
pd.pivot_table(student, values='marks', index='name', columns='country', aggfunc='mean')

country  India
name
Aman      90.0
Naman     76.0
Parv     100.0

## Q93. Use multiple aggregation functions in pivot.
> 💡 **Hint:** Pass a list to `aggfunc`: `aggfunc=["mean","max"]` — the result will have a MultiLevel column header.

In [170]:
pd.pivot_table(student, values='marks', index='name', columns='country', aggfunc=["mean","max"])

          mean   max
country  India India
name
Aman      90.0    90
Naman     76.0    76
Parv     100.0   100

## Q94. Handle missing values in pivot tables.
> 💡 **Hint:** Use `fill_value=0` in `pivot_table()` to replace NaN with a specific value.

In [171]:
pd.pivot_table(student, values='LPA', index='name', columns='marks', aggfunc='mean', fill_value=0)

marks  76    90    100
name
Aman   0.0  10.0   0.0
Naman  5.0   0.0   0.0
Parv   0.0   0.0  14.0

## Q95. Add margins (totals) in pivot tables.
> 💡 **Hint:** `margins=True, margins_name="TOTAL"` in `pivot_table()` adds a summary row and column.

In [199]:
student

        iq  marks  LPA country  iq + marks
name
Aman   100     90   10   India         190
Parv   120    100   14   India         220
Naman   80     76    5   India         156

In [175]:
pd.pivot_table(student, values='marks', index='LPA', columns='country', aggfunc=["mean"], margins=True,margins_name='Total')

               mean
country       India       Total
LPA
5         76.000000   76.000000
10        90.000000   90.000000
14       100.000000  100.000000
Total     88.666667   88.666667

## Q96. Create multi-level pivot table.
> 💡 **Hint:** Pass lists to `index` and `columns` parameters: `index=["col1","col2"], columns=["col3"]`.

In [177]:
pd.pivot_table(student, values='marks', index=['name','iq'], columns='country', aggfunc='mean')

country    India
name  iq
Aman  100   90.0
Naman 80    76.0
Parv  120  100.0

## Q97. Convert DataFrame to pivot format.
> 💡 **Hint:** `df.pivot(index="row_key", columns="col_key", values="value")` — requires **unique** combinations of row/column keys (no aggregation).

In [186]:
pd.pivot(student,index='country',columns='iq',values='marks')

iq       80   100  120
country
India     76   90  100

## Q98. Compare pivot vs groupby.
> 💡 **Hint:** `groupby()` is more flexible and returns a flat structure. `pivot_table()` gives a 2D grid and handles duplicates with aggregation. `pivot()` does **no aggregation** and fails on duplicates.

In [189]:
student.groupby('marks')['LPA'].agg(lambda x : x + 100)

marks
76     105
90     110
100    114
Name: LPA, dtype: int64

### Q99. Build summary report using pivot table.
> 💡 **Hint:** Combine `pivot_table()` with `margins=True` and `fill_value=0`. Chain `.round(2)` for presentation. Export with `.to_csv()` or `.to_excel()`.

In [190]:
summary_report = pd.pivot_table(student, values='marks', index='LPA', columns='country', aggfunc="mean", margins=True,margins_name='Total',fill_value=0)

summary_report = summary_report.round(2)

summary_report.to_csv('Datasets\summary_report.csv')

<>:5: SyntaxWarning: "\s" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\s"? A raw string is also an option.
<>:5: SyntaxWarning: "\s" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\s"? A raw string is also an option.
C:\Users\himan\AppData\Local\Temp\ipykernel_3396\3595954822.py:5: SyntaxWarning: "\s" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\s"? A raw string is also an option.
  summary_report.to_csv('Datasets\summary_report.csv')

### Q100. Create an end-to-end analysis workflow.
> 💡 **Hint:** Follow this pipeline:  
> 1. Load data → 2. Inspect (shape, dtypes, nulls) → 3. Clean (fillna, drop_duplicates) → 4. Feature engineer → 5. GroupBy/pivot analysis → 6. Sort and rank → 7. Export results.

In [195]:
student.to_csv('Datasets\student.csv')

<>:1: SyntaxWarning: "\s" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\s"? A raw string is also an option.
<>:1: SyntaxWarning: "\s" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\s"? A raw string is also an option.
C:\Users\himan\AppData\Local\Temp\ipykernel_3396\3991663928.py:1: SyntaxWarning: "\s" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\s"? A raw string is also an option.
  student.to_csv('Datasets\student.csv')

In [198]:
# ==========================================
# 1. LOAD DATA
# ==========================================
# Read the raw source data into a DataFrame
df = pd.read_csv("Datasets\student.csv")

# ==========================================
# 2. INSPECT DATA
# ==========================================
# Check dimensions, column profiles, and integrity counters
print("Dataset Shape:", df.shape)
print("\nData Types:\n", df.dtypes)
print("\nMissing Values Count:\n", df.isnull().sum())

# ==========================================
# 3. CLEAN DATA
# ==========================================
# Standardise text casing to ensure reliable groupings
df["name"] = df["name"].str.strip().str.title()
df["country"] = df["country"].str.strip().str.title()

# Rectify missing fields using column-specific strategies
df["iq"] = df["iq"].fillna(df["iq"].median())
df["marks"] = df["marks"].fillna(df["marks"].mean())
df["LPA"] = df["LPA"].fillna(0)

# Purge redundant record rows from the system
df = df.drop_duplicates(keep="first")

# ==========================================
# 4. FEATURE ENGINEER
# ==========================================
# Create advanced derived metrics for deep categorical analysis
df["total_score"] = df["iq"] + df["marks"]
df["efficiency_ratio"] = (df["LPA"] / df["total_score"]).round(4)

# ==========================================
# 5. GROUPBY / PIVOT ANALYSIS
# ==========================================
# Agglomerate metrics into structured matrices with margins
summary_pivot = pd.pivot_table(
    df,
    values=["LPA", "total_score"],
    index="country",
    aggfunc={"LPA": "mean", "total_score": "max"},
    margins=True,
    margins_name="Global Baseline",
    fill_value=0,
)

# ==========================================
# 6. SORT AND RANK
# ==========================================
# Isolate operational rows from summary blocks to perform rankings
analysis_data = summary_pivot.drop("Global Baseline", errors="ignore")

# Sort records based on financial returns
sorted_analysis = analysis_data.sort_values(by="LPA", ascending=False)

# Assign global performance rankings
sorted_analysis["regional_rank"] = (
    sorted_analysis["LPA"].rank(ascending=False, method="dense").astype(int)
)

# Final formatting clean-up
final_report = sorted_analysis.round(2)

# ==========================================
# 7. EXPORT RESULTS
# ==========================================
# Deliver formatted documents to local storage arrays
final_report.to_csv("regional_student_analysis.csv", index=True)
# final_report.to_excel("regional_student_analysis.xlsx", index=True)

print("\n--- Pipeline Completed: Final Analytical Matrix ---")
print(final_report)

Dataset Shape: (3, 6)

Data Types:
 name            str
iq            int64
marks         int64
LPA           int64
country         str
iq + marks    int64
dtype: object

Missing Values Count:
 name          0
iq            0
marks         0
LPA           0
country       0
iq + marks    0
dtype: int64

--- Pipeline Completed: Final Analytical Matrix ---
          LPA  total_score  regional_rank
country
India    9.67          220              1

<>:5: SyntaxWarning: "\s" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\s"? A raw string is also an option.
<>:5: SyntaxWarning: "\s" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\s"? A raw string is also an option.
C:\Users\himan\AppData\Local\Temp\ipykernel_3396\103701336.py:5: SyntaxWarning: "\s" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\s"? A raw string is also an option.
  df = pd.read_csv("Datasets\student.csv")